title: MTHS TSA
email: jnac8080@gmail.com
description: >-
  Information and updates on the Mountlake Terrace High School (MTHS) Technology Student Association (TSA) chapter.
baseurl: ""
url: "https://mths-tsa.github.io"
github_username:  MTHS-TSA

theme: 
plugins:
  - jekyll-feed